debug: false
management.endpoints.web.exposure.include: "*"

spring:
  datasource:
    username: bookclub
    password: bookclub
    url: jdbc:mysql://localhost:3307/bookclub
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true
    

 

     
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace

    
data.rest:
   base-path: /api
   detection-strategy: annotated
   
sql.init.mode: always


    
thymeleaf3.decoupled-logic: true