debug: false

spring:
  datasource:
    username: june
    password: Ipoi1201?
    url: jdbc:mysql://localhost:3307/board
    driver-class-name: org.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
 # mail:
 #   host: smtp.gmail.com
 #   port: 587
 #   username: account-created
 #   password: app-password-issued
 #   properties:
 #     mail.smtp.auth: true
 #     mail.smtp.timeout: 5000
 #     mail.smtp.starttls.enable: true
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
app:
  host: http://localhost:8080
server:
  tomcat:
    max-http-form-post-size: 5MB
    
thymeleaf3.decoupled-logic: true